with source as (
    select * from {{ source('raw_sources', 'raw_sales_report') }}
)

select
    id,
    cast(realizationreport_id as bigint) as realizationreport_id,
    suppliercontract_code,
    cast(rrd_id as bigint) as rrd_id,
    cast(gi_id as bigint) as gi_id,
    subject_name,
    cast(nm_id as integer) as nm_id,
    brand_name,
    sa_name,
    ts_name,
    cast(barcode as bigint) as barcode,
    doc_type_name,
    cast(quantity as integer) as quantity,
    cast(retail_price as numeric) as retail_price,
    cast(retail_amount as numeric) as retail_amount,
    cast(sale_percent as numeric) as sale_percent,
    cast(commission_percent as numeric) as commission_percent,
    office_name,
    supplier_oper_name,
    cast(order_dt as timestamp) as order_dt,
    cast(sale_dt as timestamp) as sale_dt,
    cast(rr_dt as timestamp) as rr_dt,
    cast(shk_id as bigint) as shk_id,
    cast(retail_price_withdisc_rub as numeric) as retail_price_withdisc_rub,
    cast(delivery_amount as numeric) as delivery_amount,
    cast(return_amount as numeric) as return_amount,
    cast(delivery_rub as numeric) as delivery_rub,
    gi_box_type_name,
    cast(product_discount_for_report as numeric) as product_discount_for_report,
    cast(supplier_promo as numeric) as supplier_promo,
    rid,
    cast(ppvz_spp_prc as numeric) as ppvz_spp_prc,
    cast(ppvz_kvw_prc_base as numeric) as ppvz_kvw_prc_base,
    cast(ppvz_kvw_prc as numeric) as ppvz_kvw_prc,
    cast(ppvz_sales_commission as numeric) as ppvz_sales_commission,
    cast(ppvz_for_pay as numeric) as ppvz_for_pay,
    cast(ppvz_reward as numeric) as ppvz_reward,
    cast(ppvz_vw as numeric) as ppvz_vw,
    cast(ppvz_vw_nds as numeric) as ppvz_vw_nds,
    cast(ppvz_office_id as bigint) as ppvz_office_id,
    ppvz_office_name,
    cast(ppvz_supplier_id as bigint) as ppvz_supplier_id,
    declaration_number,
    cast(sticker_id as bigint) as sticker_id,
    ppvz_supplier_name,
    ppvz_inn,
    bonus_type_name,
    cast(dag_date as date) as dag_date,
    site_country,
    cast(penalty as numeric) as penalty,
    cast(additional_payment as numeric) as additional_payment,
    srid,
    cast(date_from as date) as date_from,
    cast(date_to as date) as date_to
from source